apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: backend-service
{{ include "app.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "chart.selector" . | indent 4 }}
  ports:
    - name: http
      port: 5000
      targetPort: http