apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Chart.Name }}-0
  labels:
    app.kubernetes.io/component: database
{{ include "app.labels" . | indent 4 }}
spec:
  storageClassName: sc-{{ .Chart.Name }}
  capacity: 
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/minikube/pgsql
    type: DirectoryOrCreate