apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-db-pg-0
spec:
  storageClassName: db-pg
  capacity: 
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/minikube/pgsql
    type: DirectoryOrCreate