apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pg-1
spec:
  storageClassName: db-pg
  capacity: 
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.config.dataPath }}
    type: DirectoryOrCreate