apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: database
{{ include "app.labelsWithVersion" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
{{ include "chart.selectorWithVersion" . | indent 4 }}
  ports:
    - name: tcp
      port: 5432
      targetPort: tcp