apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.services.db }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  clusterIP: none
  selector:
    {{ include "chart.selector" . }}
  ports:
    - name: tcp
      port: 5432
      targetPort: tcp