apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: database
{{ include "app.labelsWithVersion" . | indent 4 }}
spec:
  serviceName: svc-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
{{ include "chart.selectorWithVersion" . | indent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/component: database
{{ include "app.labelsWithVersion" . | indent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:14.4-alpine
          ports:
            - name: tcp
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-{{ .Chart.Name }}
                  key: login
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-{{ .Chart.Name }}
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: sc-{{ .Chart.Name }}
        resources:
          requests:
            storage: 128Mi
        accessModes:
          - ReadWriteOnce