apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/component: database
{{ include "app.labels" . | indent 4 }}
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate